// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.
import { definePrivilegedContracts, z } from "@hatch/space-sdk";

export const privileged = definePrivilegedContracts({
  hashPassword: {
    request: z.object({ password: z.string().min(1).max(128) }),
    response: z.object({ passwordHash: z.string() }),
    timeoutMs: 30_000,
  },
  verifyPassword: {
    request: z.object({ password: z.string().min(1).max(128), passwordHash: z.string() }),
    response: z.object({ valid: z.boolean() }),
    timeoutMs: 30_000,
  },
});
